"""added new_field to messages

Revision ID: d9bb48cfea1f
Revises: 9526b9d058a9
Create Date: 2018-06-09 20:20:06.333608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9bb48cfea1f'
down_revision = '9526b9d058a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('new_field', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'new_field')
    # ### end Alembic commands ###
